pipeline:
  build-site:
    image: ruby
    commands: 
      - bundle install --path=vendor/bundle
      - bundle exec jekyll build

  build-docs:
    image: fpfis/php56-dev
    commands:
      - cd phpdoc
      - yum install -y graphviz 
      - wget https://www.phpdoc.org/phpDocumentor.phar -qO phpdoc.phar
      - composer install --ansi
      - php phpdoc.phar --ansi
      - find doc/ -name '*.dat' -delete
      - rsync -a doc/ ../_site/libs/ 

  deploy-site:
    image: fpfis/drone-plugin-git-deploy
    source: _site
    target_repo: git@github.com:fpfis/public-documentation.git
    target_folder: deployed
    clean: true
    secrets: [ deploy_key ]
    message: "Published ${DRONE_COMMIT_SHA} [CI SKIP]"
    target_branch: gh-pages
    excludes:
      - CNAME
    when:
      event: push
      branch: master
