baseURL = "https://docs.fpfis.eu/"
languageCode = "en-us"
title = "FPFIS Documentation"
theme = "hugo-theme-learn"
author = "FPFIS"
description = "FPFIS Opensource projects documentation"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"